travis:
  secure:
    BINSTAR_TOKEN: eX/XH0efAd3mTRXxFoIY5ho4n7GxW5oAfwwDeXyIcFQzgnDJOCzWxr+wGtE8D3T26IVTtE0S5/jMmdxcFPobkNU/kUvGODvyD4K0fCtC+gSTOfnWVopFNVy8+x21/QNOgKCeVMQWK23rr73qF4EFwi9OEOGa7HRzBdqfACgc7MVXtsyn3yQf/tT7SMEJqZroq71Z188lKHveE4j+Wd2nY1eebsNoXRw8MZ5/VcaLj5tYAjEX1noUFf3KyVpEGXBf8rRKzpLPsgqG8k7pYYNGN+6SR5a+IBbZnsq7R60iDL/4RUJ6nL6Oq6m/EkQ38mru/N/l3iwO4NCtyr87z4l2zjIKI2ggcC81/XVxurkpv4InSSWzZIANLMezkQLWQbSQb0oCK3u1DTbuqjobg1ZQ6TNemADW9+S4cRNGvG3rHmUpw0ZQn43qNkzdAD7mjcsuwKvTiN1xs/FlJkc57nZkjfTadUNTD1WoIAyqE6UWcC5gddgkOjujMq3+VCeB+jeVClYc8CVYyIbFfG05HtVnrgVpuu6z8iADnSfzGb+NqkZ2/cmMilOIpa6bMeebyFIeuVNb34LfyHglXqly+dyZMvNFMNfrw4IyrkG8BWZ4UxZZpGw3IpDS0BqaLthJX+5XEn6ByNKsBRhNJWtIsNVakouF/uErCUSKfpWDCRKTeqg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
